export const BASE_URL = 'http://103.171.97.71/api/v1';

export const GlobalText = {
  login: {
    title: 'Welcome Back',
    subtitle: 'Enter your credentials to manage attendance',
    emailLabel: 'Employee Email',
    emailPlaceholder: 'Enter your email',
    sendOtpButton: 'Send OTP',
  },
  otp: {
    title: 'Verify Your Account',
    subtitle: 'Enter the OTP sent to your email',
    otpLabel: 'Enter OTP',
    otpPlaceholder: 'Enter 6-digit OTP',
    verifyButton: 'Verify OTP',
    resendButton: 'Resend OTP',
  },
  home: {
    welcomeBack: 'Welcome back,',
    currentTime: 'CURRENT TIME',
    quickActions: 'QUICK ACTIONS',
    todaysActivity: "TODAY'S ACTIVITY",
    noActivity: 'No activity recorded today',
    dailyPunch: 'Daily Punch',
    idleTracking: 'Break Time',
    leaveManagement: 'Leave',
    reports: 'Reports',
  },
  dashboard: {
    welcome: 'Welcome, {name}!',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    lastCheckIn: 'Last Check-In: {time}',
    lastCheckOut: 'Last Check-Out: {time}',
    attendanceSummary: 'Attendance Summary',
    present: 'Present',
    absent: 'Absent',
    leave: 'Leave',
  },
  punch: {
    title: 'Daily Punch-In / Punch-Out',
    subtitle: 'Complete multi-step verification to mark attendance',
    startButton: 'Start Punch In',
    info: 'Please ensure you have good lighting and your face is clearly visible',
    locationStep: 'Location',
    cameraStep: 'Camera',
    uploadStep: 'Upload',
  },
  attendance: {
    currentStatus: 'CURRENT STATUS',
    notPunched: 'Not Punched In',
    punchedIn: 'Punched In',
    punchedOut: 'Punched Out',
    punchIn: 'Punch In',
    punchOut: 'Punch Out',
    readyToSync: 'Ready To Sync',
    active: 'ACTIVE',
    verificationSteps: 'VERIFICATION STEPS',
    locationStep: 'Location',
    cameraStep: 'Camera',
    verifyStep: 'Verify',
    uploading: 'Uploading',
    defaultLocation: 'HO - Chandigarh',
    locationStep: 'Location',
    selfieStep: 'Selfie',
    uploadStep: 'Upload',
  },
  alerts: {
    invalidEmail: 'Please enter a valid email address.',
    otpSent: 'OTP has been sent to your email.',
    otpVerified: 'OTP verified successfully!',
    otpError: 'Invalid OTP. Please try again.',
    networkError: 'Network error. Please check your connection.',
    serverError: 'Server error. Please try again later.',
    sessionExpired: 'Session expired. Please login again.',
    logoutConfirm: 'Are you sure you want to logout?',
    logoutSuccess: 'Logged out successfully',
    logoutError: 'Logout failed. Please try again.',
  },
  buttons: {
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    logout: 'Logout',
    verify: 'Verify',
    send: 'Send',
  },
};

export const Colors = {
  primary: '#FACC15',
  otpBorder: '#68644e',
  secondary: '#FEE440',
  background: '#0A1128',
  surface: 'rgba(38, 50, 86, 0.66)',
  textPrimary: '#FFFFFF',
  textSecondary: '#9CA3AF',
  textDark: '#0A1128',
  disabled: '#69778a',
  success: '#10B981',
  error: '#ff5656',
  warning: '#F59E0B',
  info: '#3B82F6',
  border: '#ffffff1f',
  shadow: '#000000',
  icon: '#FEE440',
  iconTitle: '#CBD5E1',
};

export const Fonts = {
  medium: 'GothamMedium',
  light: 'GothamLight',
  regular: 'GothamBook',
  bold: 'GothamBold',
};
